name: cinemana_app
description: Cinema app with Albox backend
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.1
  video_player: ^2.8.3
  chewie: ^1.7.4
  go_router: ^13.0.0
  provider: ^6.1.2
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
